insert into country(id,name,iso3Code) values (1,'Afghanistan','AFG');
insert into country(id,name,iso3Code) values (2,'Albania','ALB');
insert into country(id,name,iso3Code) values (3,'Algeria','DZA');
insert into country(id,name,iso3Code) values (4,'American Samoa','ASM');
insert into country(id,name,iso3Code) values (5,'Andorra','AND');
insert into country(id,name,iso3Code) values (6,'Angola','AGO');
insert into country(id,name,iso3Code) values (7,'Anguilla','AIA');
insert into country(id,name,iso3Code) values (8,'Antarctica','ATA');
insert into country(id,name,iso3Code) values (9,'Antigua and Barbuda','ATG');
insert into country(id,name,iso3Code) values (10,'Argentina','ARG');
insert into country(id,name,iso3Code) values (11,'Armenia','ARM');
insert into country(id,name,iso3Code) values (12,'Aruba','ABW');
insert into country(id,name,iso3Code) values (13,'Australia','AUS');
insert into country(id,name,iso3Code) values (14,'Austria','AUT');
insert into country(id,name,iso3Code) values (15,'Azerbaijan','AZE');
insert into country(id,name,iso3Code) values (16,'Bahamas (the)','BHS');
insert into country(id,name,iso3Code) values (17,'Bahrain','BHR');
insert into country(id,name,iso3Code) values (18,'Bangladesh','BGD');
insert into country(id,name,iso3Code) values (19,'Barbados','BRB');
insert into country(id,name,iso3Code) values (20,'Belarus','BLR');
insert into country(id,name,iso3Code) values (21,'Belgium','BEL');
insert into country(id,name,iso3Code) values (22,'Belize','BLZ');
insert into country(id,name,iso3Code) values (23,'Benin','BEN');
insert into country(id,name,iso3Code) values (24,'Bermuda','BMU');
insert into country(id,name,iso3Code) values (25,'Bhutan','BTN');
insert into country(id,name,iso3Code) values (26,'Bolivia (Plurinational State of)','BOL');
insert into country(id,name,iso3Code) values (27,'Bonaire, Sint Eustatius and Saba','BES');
insert into country(id,name,iso3Code) values (28,'Bosnia and Herzegovina','BIH');
insert into country(id,name,iso3Code) values (29,'Botswana','BWA');
insert into country(id,name,iso3Code) values (30,'Bouvet Island','BVT');
insert into country(id,name,iso3Code) values (31,'Brazil','BRA');
insert into country(id,name,iso3Code) values (32,'British Indian Ocean Territory (the)','IOT');
insert into country(id,name,iso3Code) values (33,'Brunei Darussalam','BRN');
insert into country(id,name,iso3Code) values (34,'Bulgaria','BGR');
insert into country(id,name,iso3Code) values (35,'Burkina Faso','BFA');
insert into country(id,name,iso3Code) values (36,'Burundi','BDI');
insert into country(id,name,iso3Code) values (37,'Cabo Verde','CPV');
insert into country(id,name,iso3Code) values (38,'Cambodia','KHM');
insert into country(id,name,iso3Code) values (39,'Cameroon','CMR');
insert into country(id,name,iso3Code) values (40,'Canada','CAN');
insert into country(id,name,iso3Code) values (41,'Cayman Islands (the)','CYM');
insert into country(id,name,iso3Code) values (42,'Central African Republic (the)','CAF');
insert into country(id,name,iso3Code) values (43,'Chad','TCD');
insert into country(id,name,iso3Code) values (44,'Chile','CHL');
insert into country(id,name,iso3Code) values (45,'China','CHN');
insert into country(id,name,iso3Code) values (46,'Christmas Island','CXR');
insert into country(id,name,iso3Code) values (47,'Cocos (Keeling) Islands (the)','CCK');
insert into country(id,name,iso3Code) values (48,'Colombia','COL');
insert into country(id,name,iso3Code) values (49,'Comoros (the)','COM');
insert into country(id,name,iso3Code) values (50,'Congo (the Democratic Republic of the)','COD');
insert into country(id,name,iso3Code) values (51,'Congo (the)','COG');
insert into country(id,name,iso3Code) values (52,'Cook Islands (the)','COK');
insert into country(id,name,iso3Code) values (53,'Costa Rica','CRI');
insert into country(id,name,iso3Code) values (54,'Croatia','HRV');
insert into country(id,name,iso3Code) values (55,'Cuba','CUB');
insert into country(id,name,iso3Code) values (56,'Curaçao','CUW');
insert into country(id,name,iso3Code) values (57,'Cyprus','CYP');
insert into country(id,name,iso3Code) values (58,'Czechia','CZE');
insert into country(id,name,iso3Code) values (59,'Côte dIvoire','CIV');
insert into country(id,name,iso3Code) values (60,'Denmark','DNK');
insert into country(id,name,iso3Code) values (61,'Djibouti','DJI');
insert into country(id,name,iso3Code) values (62,'Dominica','DMA');
insert into country(id,name,iso3Code) values (63,'Dominican Republic (the)','DOM');
insert into country(id,name,iso3Code) values (64,'Ecuador','ECU');
insert into country(id,name,iso3Code) values (65,'Egypt','EGY');
insert into country(id,name,iso3Code) values (66,'El Salvador','SLV');
insert into country(id,name,iso3Code) values (67,'Equatorial Guinea','GNQ');
insert into country(id,name,iso3Code) values (68,'Eritrea','ERI');
insert into country(id,name,iso3Code) values (69,'Estonia','EST');
insert into country(id,name,iso3Code) values (70,'Eswatini','SWZ');
insert into country(id,name,iso3Code) values (71,'Ethiopia','ETH');
insert into country(id,name,iso3Code) values (72,'Falkland Islands (the) [Malvinas]','FLK');
insert into country(id,name,iso3Code) values (73,'Faroe Islands (the)','FRO');
insert into country(id,name,iso3Code) values (74,'Fiji','FJI');
insert into country(id,name,iso3Code) values (75,'Finland','FIN');
insert into country(id,name,iso3Code) values (76,'France','FRA');
insert into country(id,name,iso3Code) values (77,'French Guiana','GUF');
insert into country(id,name,iso3Code) values (78,'French Polynesia','PYF');
insert into country(id,name,iso3Code) values (79,'French Southern Territories (the)','ATF');
insert into country(id,name,iso3Code) values (80,'Gabon','GAB');
insert into country(id,name,iso3Code) values (81,'Gambia (the)','GMB');
insert into country(id,name,iso3Code) values (82,'Georgia','GEO');
insert into country(id,name,iso3Code) values (83,'Germany','DEU');
insert into country(id,name,iso3Code) values (84,'Ghana','GHA');
insert into country(id,name,iso3Code) values (85,'Gibraltar','GIB');
insert into country(id,name,iso3Code) values (86,'Greece','GRC');
insert into country(id,name,iso3Code) values (87,'Greenland','GRL');
insert into country(id,name,iso3Code) values (88,'Grenada','GRD');
insert into country(id,name,iso3Code) values (89,'Guadeloupe','GLP');
insert into country(id,name,iso3Code) values (90,'Guam','GUM');
insert into country(id,name,iso3Code) values (91,'Guatemala','GTM');
insert into country(id,name,iso3Code) values (92,'Guernsey','GGY');
insert into country(id,name,iso3Code) values (93,'Guinea','GIN');
insert into country(id,name,iso3Code) values (94,'Guinea-Bissau','GNB');
insert into country(id,name,iso3Code) values (95,'Guyana','GUY');
insert into country(id,name,iso3Code) values (96,'Haiti','HTI');
insert into country(id,name,iso3Code) values (97,'Heard Island and McDonald Islands','HMD');
insert into country(id,name,iso3Code) values (98,'Holy See (the)','VAT');
insert into country(id,name,iso3Code) values (99,'Honduras','HND');
insert into country(id,name,iso3Code) values (100,'Hong Kong','HKG');
insert into country(id,name,iso3Code) values (101,'Hungary','HUN');
insert into country(id,name,iso3Code) values (102,'Iceland','ISL');
insert into country(id,name,iso3Code) values (103,'India','IND');
insert into country(id,name,iso3Code) values (104,'Indonesia','IDN');
insert into country(id,name,iso3Code) values (105,'Iran (Islamic Republic of)','IRN');
insert into country(id,name,iso3Code) values (106,'Iraq','IRQ');
insert into country(id,name,iso3Code) values (107,'Ireland','IRL');
insert into country(id,name,iso3Code) values (108,'Isle of Man','IMN');
insert into country(id,name,iso3Code) values (109,'Israel','ISR');
insert into country(id,name,iso3Code) values (110,'Italy','ITA');
insert into country(id,name,iso3Code) values (111,'Jamaica','JAM');
insert into country(id,name,iso3Code) values (112,'Japan','JPN');
insert into country(id,name,iso3Code) values (113,'Jersey','JEY');
insert into country(id,name,iso3Code) values (114,'Jordan','JOR');
insert into country(id,name,iso3Code) values (115,'Kazakhstan','KAZ');
insert into country(id,name,iso3Code) values (116,'Kenya','KEN');
insert into country(id,name,iso3Code) values (117,'Kiribati','KIR');
insert into country(id,name,iso3Code) values (118,'Korea (the Democratic Peoples Republic of)','PRK');
insert into country(id,name,iso3Code) values (119,'Korea (the Republic of)','KOR');
insert into country(id,name,iso3Code) values (120,'Kuwait','KWT');
insert into country(id,name,iso3Code) values (121,'Kyrgyzstan','KGZ');
insert into country(id,name,iso3Code) values (122,'Lao Peoples Democratic Republic (the)','LAO');
insert into country(id,name,iso3Code) values (123,'Latvia','LVA');
insert into country(id,name,iso3Code) values (124,'Lebanon','LBN');
insert into country(id,name,iso3Code) values (125,'Lesotho','LSO');
insert into country(id,name,iso3Code) values (126,'Liberia','LBR');
insert into country(id,name,iso3Code) values (127,'Libya','LBY');
insert into country(id,name,iso3Code) values (128,'Liechtenstein','LIE');
insert into country(id,name,iso3Code) values (129,'Lithuania','LTU');
insert into country(id,name,iso3Code) values (130,'Luxembourg','LUX');
insert into country(id,name,iso3Code) values (131,'Macao','MAC');
insert into country(id,name,iso3Code) values (132,'Madagascar','MDG');
insert into country(id,name,iso3Code) values (133,'Malawi','MWI');
insert into country(id,name,iso3Code) values (134,'Malaysia','MYS');
insert into country(id,name,iso3Code) values (135,'Maldives','MDV');
insert into country(id,name,iso3Code) values (136,'Mali','MLI');
insert into country(id,name,iso3Code) values (137,'Malta','MLT');
insert into country(id,name,iso3Code) values (138,'Marshall Islands (the)','MHL');
insert into country(id,name,iso3Code) values (139,'Martinique','MTQ');
insert into country(id,name,iso3Code) values (140,'Mauritania','MRT');
insert into country(id,name,iso3Code) values (141,'Mauritius','MUS');
insert into country(id,name,iso3Code) values (142,'Mayotte','MYT');
insert into country(id,name,iso3Code) values (143,'Mexico','MEX');
insert into country(id,name,iso3Code) values (144,'Micronesia (Federated States of)','FSM');
insert into country(id,name,iso3Code) values (145,'Moldova (the Republic of)','MDA');
insert into country(id,name,iso3Code) values (146,'Monaco','MCO');
insert into country(id,name,iso3Code) values (147,'Mongolia','MNG');
insert into country(id,name,iso3Code) values (148,'Montenegro','MNE');
insert into country(id,name,iso3Code) values (149,'Montserrat','MSR');
insert into country(id,name,iso3Code) values (150,'Morocco','MAR');
insert into country(id,name,iso3Code) values (151,'Mozambique','MOZ');
insert into country(id,name,iso3Code) values (152,'Myanmar','MMR');
insert into country(id,name,iso3Code) values (153,'Namibia','NAM');
insert into country(id,name,iso3Code) values (154,'Nauru','NRU');
insert into country(id,name,iso3Code) values (155,'Nepal','NPL');
insert into country(id,name,iso3Code) values (156,'Netherlands (the)','NLD');
insert into country(id,name,iso3Code) values (157,'New Caledonia','NCL');
insert into country(id,name,iso3Code) values (158,'New Zealand','NZL');
insert into country(id,name,iso3Code) values (159,'Nicaragua','NIC');
insert into country(id,name,iso3Code) values (160,'Niger (the)','NER');
insert into country(id,name,iso3Code) values (161,'Nigeria','NGA');
insert into country(id,name,iso3Code) values (162,'Niue','NIU');
insert into country(id,name,iso3Code) values (163,'Norfolk Island','NFK');
insert into country(id,name,iso3Code) values (164,'Northern Mariana Islands (the)','MNP');
insert into country(id,name,iso3Code) values (165,'Norway','NOR');
insert into country(id,name,iso3Code) values (166,'Oman','OMN');
insert into country(id,name,iso3Code) values (167,'Pakistan','PAK');
insert into country(id,name,iso3Code) values (168,'Palau','PLW');
insert into country(id,name,iso3Code) values (169,'Palestine, State of','PSE');
insert into country(id,name,iso3Code) values (170,'Panama','PAN');
insert into country(id,name,iso3Code) values (171,'Papua New Guinea','PNG');
insert into country(id,name,iso3Code) values (172,'Paraguay','PRY');
insert into country(id,name,iso3Code) values (173,'Peru','PER');
insert into country(id,name,iso3Code) values (174,'Philippines (the)','PHL');
insert into country(id,name,iso3Code) values (175,'Pitcairn','PCN');
insert into country(id,name,iso3Code) values (176,'Poland','POL');
insert into country(id,name,iso3Code) values (177,'Portugal','PRT');
insert into country(id,name,iso3Code) values (178,'Puerto Rico','PRI');
insert into country(id,name,iso3Code) values (179,'Qatar','QAT');
insert into country(id,name,iso3Code) values (180,'Republic of North Macedonia','MKD');
insert into country(id,name,iso3Code) values (181,'Romania','ROU');
insert into country(id,name,iso3Code) values (182,'Russian Federation (the)','RUS');
insert into country(id,name,iso3Code) values (183,'Rwanda','RWA');
insert into country(id,name,iso3Code) values (184,'Réunion','REU');
insert into country(id,name,iso3Code) values (185,'Saint Barthélemy','BLM');
insert into country(id,name,iso3Code) values (186,'Saint Helena, Ascension and Tristan da Cunha','SHN');
insert into country(id,name,iso3Code) values (187,'Saint Kitts and Nevis','KNA');
insert into country(id,name,iso3Code) values (188,'Saint Lucia','LCA');
insert into country(id,name,iso3Code) values (189,'Saint Martin (French part)','MAF');
insert into country(id,name,iso3Code) values (190,'Saint Pierre and Miquelon','SPM');
insert into country(id,name,iso3Code) values (191,'Saint Vincent and the Grenadines','VCT');
insert into country(id,name,iso3Code) values (192,'Samoa','WSM');
insert into country(id,name,iso3Code) values (193,'San Marino','SMR');
insert into country(id,name,iso3Code) values (194,'Sao Tome and Principe','STP');
insert into country(id,name,iso3Code) values (195,'Saudi Arabia','SAU');
insert into country(id,name,iso3Code) values (196,'Senegal','SEN');
insert into country(id,name,iso3Code) values (197,'Serbia','SRB');
insert into country(id,name,iso3Code) values (198,'Seychelles','SYC');
insert into country(id,name,iso3Code) values (199,'Sierra Leone','SLE');
insert into country(id,name,iso3Code) values (200,'Singapore','SGP');
insert into country(id,name,iso3Code) values (201,'Sint Maarten (Dutch part)','SXM');
insert into country(id,name,iso3Code) values (202,'Slovakia','SVK');
insert into country(id,name,iso3Code) values (203,'Slovenia','SVN');
insert into country(id,name,iso3Code) values (204,'Solomon Islands','SLB');
insert into country(id,name,iso3Code) values (205,'Somalia','SOM');
insert into country(id,name,iso3Code) values (206,'South Africa','ZAF');
insert into country(id,name,iso3Code) values (207,'South Georgia and the South Sandwich Islands','SGS');
insert into country(id,name,iso3Code) values (208,'South Sudan','SSD');
insert into country(id,name,iso3Code) values (209,'Spain','ESP');
insert into country(id,name,iso3Code) values (210,'Sri Lanka','LKA');
insert into country(id,name,iso3Code) values (211,'Sudan (the)','SDN');
insert into country(id,name,iso3Code) values (212,'Suriname','SUR');
insert into country(id,name,iso3Code) values (213,'Svalbard and Jan Mayen','SJM');
insert into country(id,name,iso3Code) values (214,'Sweden','SWE');
insert into country(id,name,iso3Code) values (215,'Switzerland','CHE');
insert into country(id,name,iso3Code) values (216,'Syrian Arab Republic','SYR');
insert into country(id,name,iso3Code) values (217,'Taiwan (Province of China)','TWN');
insert into country(id,name,iso3Code) values (218,'Tajikistan','TJK');
insert into country(id,name,iso3Code) values (219,'Tanzania United Republic of','TZA');
insert into country(id,name,iso3Code) values (220,'Thailand','THA');
insert into country(id,name,iso3Code) values (221,'Timor-Leste','TLS');
insert into country(id,name,iso3Code) values (222,'Togo','TGO');
insert into country(id,name,iso3Code) values (223,'Tokelau','TKL');
insert into country(id,name,iso3Code) values (224,'Tonga','TON');
insert into country(id,name,iso3Code) values (225,'Trinidad and Tobago','TTO');
insert into country(id,name,iso3Code) values (226,'Tunisia','TUN');
insert into country(id,name,iso3Code) values (227,'Turkey','TUR');
insert into country(id,name,iso3Code) values (228,'Turkmenistan','TKM');
insert into country(id,name,iso3Code) values (229,'Turks and Caicos Islands (the)','TCA');
insert into country(id,name,iso3Code) values (230,'Tuvalu','TUV');
insert into country(id,name,iso3Code) values (231,'Uganda','UGA');
insert into country(id,name,iso3Code) values (232,'Ukraine','UKR');
insert into country(id,name,iso3Code) values (233,'United Arab Emirates (the)','ARE');
insert into country(id,name,iso3Code) values (234,'United Kingdom of Great Britain and Northern Ireland (the)','GBR');
insert into country(id,name,iso3Code) values (235,'United States Minor Outlying Islands (the)','UMI');
insert into country(id,name,iso3Code) values (236,'United States of America (the)','USA');
insert into country(id,name,iso3Code) values (237,'Uruguay','URY');
insert into country(id,name,iso3Code) values (238,'Uzbekistan','UZB');
insert into country(id,name,iso3Code) values (239,'Vanuatu','VUT');
insert into country(id,name,iso3Code) values (240,'Venezuela (Bolivarian Republic of)','VEN');
insert into country(id,name,iso3Code) values (241,'Viet Nam','VNM');
insert into country(id,name,iso3Code) values (242,'Virgin Islands (British)','VGB');
insert into country(id,name,iso3Code) values (243,'Virgin Islands (U.S.)','VIR');
insert into country(id,name,iso3Code) values (244,'Wallis and Futuna','WLF');
insert into country(id,name,iso3Code) values (245,'Western Sahara','ESH');
insert into country(id,name,iso3Code) values (246,'Yemen','YEM');
insert into country(id,name,iso3Code) values (247,'Zambia','ZMB');
insert into country(id,name,iso3Code) values (248,'Zimbabwe','ZWE');
insert into country(id,name,iso3Code) values (249,'Åland Islands','ALA');
